### ISSUE TITLE
Модуль при обмене удаляет таблицу базы данных oc_product_price

### ISSUE THREAD

**Issue by mimaster-cmd** [KirilLoveVE/opencart2-exchange1c#50]
Opencart 2.3
При выполнении обмена в УТ 11 товары загружаются на сайт, но при открытии карточки товара на сайте выдает вида:

`Fatal error: Uncaught exception 'Exception' with message 'Error: Table 'cv62352.oc_product_price' doesn't exist<br />Error No: 1146<br />SELECT `product_feature_id`, `price`, `unit_id` FROM `oc_product_price` WHERE `product_id` = 68 AND `customer_group_id` = 1' in /home/c/cv62352/public_html/system/library/db/mysqli.php:40 Stack trace: #0 /home/c/cv62352/public_html/system/library/db.php(16): DB\MySQLi->query('SELECT `product...', Array) #1 /home/c/cv62352/public_html/system/storage/modification/catalog/controller/product/product.php(297): DB->query('SELECT `product...') #2 [internal function]: ControllerProductProduct->index() #3 /home/c/cv62352/public_html/system/storage/modification/system/engine/action.php(51): call_user_func_array(Array, Array) #4 /home/c/cv62352/public_html/system/engine/front.php(34): Action->execute(Object(Registry)) #5 /home/c/cv62352/public_html/system/engine/front.php(29): Front->execute(Object(Action)) #6 /home/c/cv62352/public_html/syste in /home/c/cv62352/public_html/system/library/db/mysqli.php on line 40`

Восстанавливаю oc_product_price и сопутствующие реквизиты в phpmyadmin - карточки начинают работать, правда без цен, из-за этого бага дальше продвинуться не могу.

**Comment by Tseka85** [comment]
Думаю лучше удалите версию официальную 1.6.4.7 (автор её уже не поддерживает)  и скачайте , а потом установите вот эту сборку [Сборка от @Gmp 1.6.4.8](https://opencartforum.com/topic/60560-podderzhka-modul-obmena-dlya-opencart-v23-s-uchetnoy-sistemoy-po-standartu-commerceml/?page=164&tab=comments#comment-1666326)  Это последняя не официальная сборка от @Gmp версия 1.6.4.8 . Много исправлений .

**Comment by Tseka85** [comment]
Автор вряд-ли уже тут ответит , переходите на  [форум](https://opencartforum.com/topic/60560-podderzhka-modul-obmena-dlya-opencart-v23-s-uchetnoy-sistemoy-po-standartu-commerceml/?page=174)

**Comment by mimaster-cmd** [comment]
Спасибо, попробую

**Comment by KirilLoveVE** [comment]
1.6.4.7 версия используется по сей день на моем сайте, некогда было читать записи о проблемах, только сейчас читаю некоторые когда решил обновить модуль на гитхабе после длительной обкатки на своем сайте.

По данной проблеме могу сообщить что таблица действительно не используется в версии 1.6.4.7, поэтому при сохранении настроек запускается механизм обновления, возможно возникают ошибки при обновлении с более ранних версий. Ошибка должна уйти при обновлении модуля с гитхаба.
